### ISSUE TITLE
Feature request: Configuration

### ISSUE THREAD

**Issue by SlimeDog** [jpenilla/chesscraft#11]
I manage plugin update-checking -- we have a home-grown update-checker -- and configuration and message content precisely.  For every release, I compare the new configuration with the previous (saved) to identify changes and make necessary adjustments (for example, I disable update-checking -- not relevant for ChessCraft, but bear with me -- and remove formatting codes from messages). It is very helpful if the default configuration and messages are included in the JAR. Otherwise, I have to jump through hoops to make the necessary comparisons. So, several requests:
- Separate messages into `messages.yml`.
- Include `config.yml` and `messages.yml` in the JAR.
- Configuration includes
```
pieces:
    mode: ITEM_FRAME
    material: PAPER
    height-offsets:
        QUEEN: -0.25
        KING: 0.0
        KNIGHT: -0.5625
        PAWN: -0.71875
        ROOK: -0.625
        BISHOP: -0.21875
    white-custom-model-data:
        QUEEN: 11
        KING: 12
        KNIGHT: 9
        PAWN: 7
        ROOK: 10
        BISHOP: 8
    black-custom-model-data:
        QUEEN: 5
        KING: 6
        KNIGHT: 3
        PAWN: 1
        ROOK: 4
        BISHOP: 2
```
&nbsp; &nbsp; &nbsp; &nbsp; I'm not sure why these elements are in the configuration. Would these elements ever be changed by a server owner?
- I use the resourcepack. I guess the custom-data-model entries reflect that.
